module: Add EBS extra volume support
dcos-terraform/terraform-aws-dcos pull request #45
Opened 2019-02-05 05:09 UTC by jieyu

Allow extra EBS volumes to be created for each AWS instance.

2019-02-05 15:07 UTC, fatz requested changes
see dcos-terraform/terraform-aws-instance#6

2019-02-06 11:51 UTC, fatz commented on main.tf
> +  private_agents_extra_volumes               = ["${var.private_agents_extra_volumes}"]
with this we need to have a minimum ref to the next version of instance

2019-02-06 12:08 UTC, fatz commented
min version of infra needs to be raised as mentioned in dcos-terraform-terraform-aws-infrastructure#20 next patch num is safe to use

2019-02-06 17:45 UTC, jieyu commented
@fatz PTAL again. I bump the dependency version

2019-02-06 18:20 UTC, fatz approved these changes
ci failed cause of a missing description update which is available in master. Approving and merging.

2019-02-06 18:20 UTC, merged

2019-05-15 06:41 UTC, Rohithzr commented
@fatz thanks, I have one question though, does this method also mounts those volumes to the instance?